import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const upstreamUrl =
  'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json';
const snapshotPath = resolve(
  import.meta.dir,
  '../src/features/model-operations/model-pricing-snapshot.ts',
);
const biomePath = resolve(import.meta.dir, '../node_modules/.bin/biome');
const supportedProviders = new Set(['openai', 'anthropic']);

type SnapshotPrice = Readonly<{
  provider: string;
  inputPerMillion: number;
  cachedInputPerMillion?: number;
  outputPerMillion: number;
}>;

type Snapshot = Readonly<{
  _source: string;
  _fetched: string;
  models: Readonly<Record<string, SnapshotPrice>>;
}>;

type UpstreamPrice = Readonly<{
  mode?: unknown;
  litellm_provider?: unknown;
  input_cost_per_token?: unknown;
  output_cost_per_token?: unknown;
  cache_read_input_token_cost?: unknown;
}>;

const isFiniteNumber = (value: unknown): value is number =>
  typeof value === 'number' && Number.isFinite(value);

const perMillion = (perToken: number): number => Number((perToken * 1_000_000).toFixed(12));

async function fetchCatalogue(): Promise<Record<string, SnapshotPrice>> {
  const response = await fetch(upstreamUrl);
  if (!response.ok) throw new Error(`HTTP ${response.status} fetching pricing catalogue.`);
  const payload = (await response.json()) as Record<string, UpstreamPrice>;
  const models: Record<string, SnapshotPrice> = {};
  for (const [model, entry] of Object.entries(payload)) {
    if (
      entry.mode !== 'chat' ||
      typeof entry.litellm_provider !== 'string' ||
      !supportedProviders.has(entry.litellm_provider) ||
      !isFiniteNumber(entry.input_cost_per_token) ||
      !isFiniteNumber(entry.output_cost_per_token)
    ) {
      continue;
    }
    models[model] = {
      provider: entry.litellm_provider,
      inputPerMillion: perMillion(entry.input_cost_per_token),
      outputPerMillion: perMillion(entry.output_cost_per_token),
      ...(isFiniteNumber(entry.cache_read_input_token_cost)
        ? { cachedInputPerMillion: perMillion(entry.cache_read_input_token_cost) }
        : {}),
    };
  }
  return Object.fromEntries(
    Object.entries(models).sort(([left], [right]) => left.localeCompare(right)),
  );
}

async function loadSnapshot(): Promise<Snapshot> {
  const loaded = await import(`${snapshotPath}?snapshot=${Date.now()}`);
  return loaded.modelPricingSnapshot as Snapshot;
}

function diff(
  current: Readonly<Record<string, SnapshotPrice>>,
  incoming: Readonly<Record<string, SnapshotPrice>>,
) {
  const currentKeys = new Set(Object.keys(current));
  const incomingKeys = new Set(Object.keys(incoming));
  const added = [...incomingKeys].filter((key) => !currentKeys.has(key));
  const removed = [...currentKeys].filter((key) => !incomingKeys.has(key));
  const changed = [...currentKeys].filter(
    (key) =>
      incoming[key] !== undefined && JSON.stringify(current[key]) !== JSON.stringify(incoming[key]),
  );
  return { added, removed, changed };
}

function serialize(snapshot: Snapshot): string {
  return `/** Generated by \`bun run update:model-pricing:write\`; do not edit manually. */\nexport const modelPricingSnapshot = ${JSON.stringify(snapshot, null, 2)} as const;\n`;
}

const incoming = await fetchCatalogue();
const current = await loadSnapshot();
const changes = diff(current.models, incoming);
console.log(
  `Pricing catalogue: ${Object.keys(incoming).length} models; ${changes.added.length} added, ${changes.changed.length} changed, ${changes.removed.length} removed.`,
);
if (!process.argv.includes('--write')) {
  if (changes.added.length + changes.changed.length + changes.removed.length > 0)
    process.exitCode = 1;
} else {
  await writeFile(
    snapshotPath,
    serialize({
      _source: upstreamUrl,
      _fetched: new Date().toISOString().slice(0, 10),
      models: incoming,
    }),
    'utf8',
  );
  const formatter = Bun.spawn([biomePath, 'format', '--write', snapshotPath], {
    stderr: 'inherit',
    stdout: 'inherit',
  });
  if ((await formatter.exited) !== 0) throw new Error('Unable to format pricing snapshot.');
  console.log('Pricing snapshot updated.');
}
